# Generated by Django 5.0.7 on 2024-09-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('term_en', models.CharField(blank=True, max_length=100, null=True)),
                ('term_kor', models.CharField(blank=True, max_length=100, null=True)),
                ('mean', models.TextField(blank=True, null=True)),
                ('detail_mean', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.TextField()),
                ('user_name', models.TextField()),
            ],
        ),
    ]
