# Generated by Django 5.0.7 on 2024-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('term_en', models.CharField(max_length=255)),
                ('term_ko', models.CharField(max_length=255)),
                ('mean', models.TextField()),
            ],
        ),
    ]
